include("test_softmax.jl")
include("test_embedding.jl")
include("test_query.jl")
include("test_WordDistributions.jl")
include("test_wordstream.jl")
include("./test_senseembeddings.jl")
include("./test_utils.jl")
include("./test_ReservoirShuffler.jl")
